### ISSUE TITLE
build for apple m1

### ISSUE THREAD

**Issue by leejw51** [yhirose/react-typescript-electron-sample-with-create-react-app-and-electron-builder#17]
how can i build for apple m1?
yarn electron:build produces x64 binary

**Comment by yhirose** [comment]
@leejw51, you have to wait until electron-builder officially supports m1. It seems some are able to make `arm` or `universal` build successfully. Could you try the suggestions described in [this electron-builder issue](https://github.com/electron-userland/electron-builder/issues/5392) on your machine, since I don't have a M1 machine? If your attempt works, I'll put the information on README. Thanks for your great help in advance!

**Comment by yhirose** [comment]
@leejw51, any update?

**Comment by yhirose** [comment]
@leejw51, I upgraded to Electron 12.0.0 and electron-builder 22.10.5 which supports M1. You can pass `--arm64` or `--universal` to electron-builder command in `electron:build` script to generate a binary for M1 according to the [this electron-builder issue](https://github.com/electron-userland/electron-builder/issues/5392). Please find more detailed info there.
