### ISSUE TITLE
Images inside electron/ are not copied over to build/

### ISSUE THREAD

**Issue by typologist** [yhirose/react-typescript-electron-sample-with-create-react-app-and-electron-builder#22]
I have an `electron/icons` folder, but it doesn't get copied to `build/` when I run `electron:dev`. Any idea why? Thanks in advance :)

**Comment by ledenmat** [comment]
I am making the assumption that your electron/icons does not contain js or ts files. I am also making the assumption that this does not work on electron:build.

The reason it is not moving over the icons folder is because tsc (command in electron:dev and electron:build that turns .ts files into .js in /build) does not move over files other than ts (and optionally tsx, jsx, and js). You will need to add a copy folder step in your script (e.g. [Using copyfiles](https://vccolombo.github.io/blog/tsc-how-to-copy-non-typescript-files-when-building/) )

**Comment by yhirose** [comment]
@typologist, hope @ced-led's comment helps you.
